version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        patterns: ["*"]

  - package-ecosystem: "pip"
    directory: "/cli"
    schedule:
      interval: "weekly"
    groups:
      pip:
        patterns: ["*"]

  - package-ecosystem: "terraform"
    directory: "/modules"
    schedule:
      interval: "weekly"
    groups:
      terraform:
        patterns: ["*"]
